name: Robo B3

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  rodar-robo:
    runs-on: ubuntu-latest
    steps:
      - name: Puxar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Executar o App
        env:
          TZ: "America/Sao_Paulo" 
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          SENHA_APP_EMAIL: ${{ secrets.SENHA_APP_EMAIL }}
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python app.py
